name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-24.04
            compiler: gcc

    steps:
    - name: Install dev dependencies
      run: sudo apt-get install -y libboost-all-dev doxygen libclang-15-dev

    - name: Checkout Code
      uses: actions/checkout@v2

    #- name: Build Boost
    #  id: boost
    #  uses: egor-tensin/build-boost@v1
    #  with:
    #    version: 1.86.0
    #    libraries: chrono filesystem log mpi program_options system thread
    #    platform: x64
    #    configuration: Release

    #- name: Show paths
    #  run: |
    #    printf 'Boost has been unpacked to: %s\n' '${{ steps.boost.outputs.root }}'
    #    printf 'Libraries can be found here: %s\n' '${{ steps.boost.outputs.librarydir }}'
    #  shell: bash

    - name: Configure (${{ matrix.configuration }})
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build --config ${{ matrix.configuration }}

    - name: Test
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest -C ${{ matrix.configuration }}
